/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.0.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.8.10"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the JUnit 5 integration.
    implementation("org.junit.jupiter:junit-jupiter:5.10.1")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("belajar.kotlin.unit.test.AppKt")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.

    useJUnitPlatform()

    // menjalankan test kecuali tag integration-test
//    useJUnitPlatform {
//        excludeTags("integration-test")
//    }
}

// menjalankan hanya integration test
tasks.register("integration-test", Test::class) {
    useJUnitPlatform {
        includeTags("integration-test")
    }
}
